"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class dex_command_lcmt(object):

    __slots__ = ["left_grip", "right_grip", "utime"]

    __typenames__ = ["int8_t", "int8_t", "int64_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.left_grip = 0
        """ LCM Type: int8_t """
        self.right_grip = 0
        """
        0=open, 1=close
        LCM Type: int8_t
        """

        self.utime = 0
        """
        0=open, 1=close
        LCM Type: int64_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(dex_command_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bbq", self.left_grip, self.right_grip, self.utime))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != dex_command_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return dex_command_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = dex_command_lcmt()
        self.left_grip, self.right_grip, self.utime = struct.unpack(">bbq", buf.read(10))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if dex_command_lcmt in parents: return 0
        tmphash = (0x86c72c7be8cf6e2f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if dex_command_lcmt._packed_fingerprint is None:
            dex_command_lcmt._packed_fingerprint = struct.pack(">Q", dex_command_lcmt._get_hash_recursive([]))
        return dex_command_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", dex_command_lcmt._get_packed_fingerprint())[0]

