"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class transformation_t(object):
    __slots__ = ["name", "pos_vicon", "quat_vicon"]

    def __init__(self):
        self.name = ""
        self.pos_vicon = [ 0.0 for dim0 in range(3) ]
        self.quat_vicon = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(transformation_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>3d', *self.pos_vicon[:3]))
        buf.write(struct.pack('>4d', *self.quat_vicon[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != transformation_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return transformation_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = transformation_t()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.pos_vicon = struct.unpack('>3d', buf.read(24))
        self.quat_vicon = struct.unpack('>4d', buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if transformation_t in parents: return 0
        tmphash = (0x13fb85b3740d0df6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if transformation_t._packed_fingerprint is None:
            transformation_t._packed_fingerprint = struct.pack(">Q", transformation_t._get_hash_recursive([]))
        return transformation_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

