"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class camera_reference_data_lcmt(object):

    __slots__ = ["cam_ref_dof_pos", "root_pos", "root_rot", "timestamp"]

    __typenames__ = ["float", "float", "float", "int64_t"]

    __dimensions__ = [[29], [3], [4], None]

    def __init__(self):
        self.cam_ref_dof_pos = [ 0.0 for dim0 in range(29) ]
        """ LCM Type: float[29] """
        self.root_pos = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.root_rot = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.timestamp = 0
        """ LCM Type: int64_t """

    def encode(self):
        buf = BytesIO()
        buf.write(camera_reference_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>29f', *self.cam_ref_dof_pos[:29]))
        buf.write(struct.pack('>3f', *self.root_pos[:3]))
        buf.write(struct.pack('>4f', *self.root_rot[:4]))
        buf.write(struct.pack(">q", self.timestamp))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != camera_reference_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return camera_reference_data_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = camera_reference_data_lcmt()
        self.cam_ref_dof_pos = struct.unpack('>29f', buf.read(116))
        self.root_pos = struct.unpack('>3f', buf.read(12))
        self.root_rot = struct.unpack('>4f', buf.read(16))
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if camera_reference_data_lcmt in parents: return 0
        tmphash = (0xb744065e545e2cfc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if camera_reference_data_lcmt._packed_fingerprint is None:
            camera_reference_data_lcmt._packed_fingerprint = struct.pack(">Q", camera_reference_data_lcmt._get_hash_recursive([]))
        return camera_reference_data_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", camera_reference_data_lcmt._get_packed_fingerprint())[0]

