defaults:
  - robot: g1_hitter_racket
  - obs: hitter
  - sim: mujoco
  - env: hitter
  - agent: hitter
  - mimic: hitter
  - _self_

device: cpu

robot:
  control:
    use_teleop: false
    viewer: false
    real_time: false
