policy:
  checkpoint: ./data/model/previous_work/gmt.pt
  action_scale: 0.5
  action_clip: 10.0
  history_length: 20

metrics_path: ./logs/metrics_gmt.csv

robot:
  default_dof_pos: [
    -0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
    -0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
    0.0, 0.0, 0.0,
    0.0, 0.4, 0.0, 1.2,
    0.0, -0.4, 0.0, 1.2
  ]

motion:
  # motion_path: ./data/motion/lafan_npz_10s_wo_getup
  motion_path: ./data/motion/lafan_g1_npz/g1__jumps1_subject1.npz
  playback_speed: 1.0
  loop: true
  total_dof: 23
  dof: 23
  ref_dof: 23
  gym_idx: true
  zero_padding_list: []
  override_robot_anchor_pos: false
  interp_steps: 0
  anchor_body_name: "torso_link"
  command_horizon: 1
  command_velocity: true
  body_names: [
    "pelvis",
    "left_hip_roll_link",
    "left_knee_link",
    "left_ankle_roll_link",
    "right_hip_roll_link",
    "right_knee_link",
    "right_ankle_roll_link",
    "torso_link",
    "left_shoulder_roll_link",
    "left_elbow_link",
    "left_wrist_yaw_link",
    "right_shoulder_roll_link",
    "right_elbow_link",
    "right_wrist_yaw_link",
  ]
  body_names_all: [
    "pelvis",
    "left_hip_pitch_link",
    "right_hip_pitch_link",
    "waist_yaw_link",
    "left_hip_roll_link",
    "right_hip_roll_link",
    "waist_roll_link",
    "left_hip_yaw_link",
    "right_hip_yaw_link",
    "torso_link",
    "left_knee_link",
    "right_knee_link",
    "left_shoulder_pitch_link",
    "right_shoulder_pitch_link",
    "left_ankle_pitch_link",
    "right_ankle_pitch_link",
    "left_shoulder_roll_link",
    "right_shoulder_roll_link",
    "left_ankle_roll_link",
    "right_ankle_roll_link",
    "left_shoulder_yaw_link",
    "right_shoulder_yaw_link",
    "left_elbow_link",
    "right_elbow_link",
    "left_wrist_roll_link",
    "right_wrist_roll_link",
    "left_wrist_pitch_link",
    "right_wrist_pitch_link",
    "left_wrist_yaw_link",
    "right_wrist_yaw_link",
  ]
